name: Docker App CI
on:
  push:
    branches: [ "main" ]
    paths:
      - 'python/**'

env:
  IMAGE_TAG: v${{ github.run_number }}

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build website image
      run: |
        docker build --platform linux --tag nachogolden/nacho_imagen:${{ env.IMAGE_TAG }} -f python/Dockerfile python/
        
    - name: Publish website image
      run: |
        docker push nachogolden/nacho_imagen:${{ env.IMAGE_TAG }}
        
    - name: App service auth
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-nacho'
        publish-profile: ${{ secrets.AZ_WEB_APP_PUBLISH_PROFILE }}
        images: 'nachogolden/nacho_imagen:${{ env.IMAGE_TAG }}'
