name: Container App Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3   

    - name: Construct Azure credentials
      id: buildcreds
      run: |
        echo "{\"clientId\":\"${{ secrets.AZ_CLIENT_ID }}\",\"clientSecret\":\"${{ secrets.AZ_CLIENT_SECRET }}\",\"subscriptionId\":\"${{ secrets.AZ_SUB_ID }}\",\"tenantId\":\"${{ secrets.AZ_TENANT_ID }}\"}" > creds.json
        echo "AZ_CREDS=$(cat creds.json)" >> $GITHUB_ENV

    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ env.AZ_CREDS }}

    - name: Verify Azure Login
      run: |
        az account show --query "{subscription: name, id: id}" --output table

    - name: Install az containerapp extension
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Python image
      run: | 
        docker build --platform linux --tag nachogolden/nacho_imagen:latest -f python/Dockerfile python/
        
    - name: Publish Docker Python image
      run: |
        docker push nachogolden/nacho_imagen:latest
        
    - name: Deploy Python container App
      run: |
        az containerapp up --name python-container-app --image nachogolden/nacho_imagen:latest --resource-group Grupo_Nacho --environment python-container-env --ingress external --target-port 5000

